<?php

/**
 * This is the model base class for the table "view_debtors_debts_clusters".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewDebtorsDebtsClusters".
 *
 * Columns in table "view_debtors_debts_clusters" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idDebtorDebt
 * @property integer $idDebtorObligation
 * @property integer $idCluster
 *
 */
abstract class BaseViewDebtorsDebtsClusters extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_debtors_debts_clusters';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewDebtorsDebtsClusters|ViewDebtorsDebtsClusters', $n);
	}

	public static function representingColumn() {
		return 'idDebtorDebt';
	}

	public function rules() {
		return array(
			array('idDebtorDebt, idDebtorObligation, idCluster', 'required'),
			array('idDebtorDebt, idDebtorObligation, idCluster', 'numerical', 'integerOnly'=>true),
			array('idDebtorDebt, idDebtorObligation, idCluster', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idDebtorDebt' => Yii::t('app', 'Id Debtor Debt'),
			'idDebtorObligation' => Yii::t('app', 'Id Debtor Obligation'),
			'idCluster' => Yii::t('app', 'Id Cluster'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idDebtorDebt', $this->idDebtorDebt);
		$criteria->compare('idDebtorObligation', $this->idDebtorObligation);
		$criteria->compare('idCluster', $this->idCluster);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}