<?php

/**
 * This is the model base class for the table "tbl_debtors_debts_obligations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsDebtsObligations".
 *
 * Columns in table "tbl_debtors_debts_obligations" available as properties of the model,
 * followed by relations of table "tbl_debtors_debts_obligations" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idDebtorDebt
 * @property integer $idDebtorObligation
 * @property string $dateCreated
 *
 * @property DebtorsDebts $idDebtorDebt0
 * @property DebtorsObligations $idDebtorObligation0
 */
abstract class BaseDebtorsDebtsObligations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_debts_obligations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsDebtsObligations|DebtorsDebtsObligations', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idDebtorDebt, idDebtorObligation, dateCreated', 'required'),
			array('idDebtorDebt, idDebtorObligation', 'numerical', 'integerOnly'=>true),
			array('id, idDebtorDebt, idDebtorObligation, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDebtorDebt0' => array(self::BELONGS_TO, 'DebtorsDebts', 'idDebtorDebt'),
			'idDebtorObligation0' => array(self::BELONGS_TO, 'DebtorsObligations', 'idDebtorObligation'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtorDebt' => null,
			'idDebtorObligation' => null,
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idDebtorDebt0' => null,
			'idDebtorObligation0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtorDebt', $this->idDebtorDebt);
		$criteria->compare('idDebtorObligation', $this->idDebtorObligation);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}