<?php

/**
 * This is the model base class for the table "tbl_debtors_property".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsProperty".
 *
 * Columns in table "tbl_debtors_property" available as properties of the model,
 * followed by relations of table "tbl_debtors_property" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUserProperty
 * @property integer $idDebtor
 * @property integer $idPropertyType
 * @property integer $idCity
 * @property string $name
 * @property string $address
 * @property string $number
 * @property string $comment
 * @property string $support
 * @property string $dateCreated
 *
 * @property Debtors $idDebtor0
 * @property PropertyType $idPropertyType0
 * @property Users $idUserProperty0
 */
abstract class BaseDebtorsProperty extends GxActiveRecord {
    
    public $idCountry;
    public $idDepartment;
    public $fullDistrict;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_property';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsProperty|DebtorsProperties', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('idUserProperty, idDebtor, idPropertyType, idCountry, idDepartment, idCity, comment', 'required'),
			array('idUserProperty, idDebtor, idPropertyType, idCity', 'numerical', 'integerOnly'=>true),
			array('name, address, number', 'length', 'max'=>500),
                        array('support', 'safe'),
                        array('support', 'match', 'pattern'=>'/\.(gif|jpg|jpeg|png|pdf|tiff)$/i','message'=>Yii::t('err','El {attribute} es inválido, Solo los archivos con estas extensiones son permitidos: gif, jpg, jpeg, png, tiff, pdf'), 'allowEmpty'=>true),			
			array('idUserProperty, idDebtor, idPropertyType, idCity, support', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUserProperty, idDebtor, idPropertyType, idCity, name, address, number, comment, support, dateCreated', 'safe', 'on'=>'search'),
		);
	}
        
        public function afterFind(){
            parent::afterFind();                        
            
            if($this->idCity!= NULL){
                $treeDistrict = ViewLocation::model()->find(array('condition' =>'idCity ='.$this->idCity));
                if($treeDistrict != NULL){
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;                    
                }                
            } 
        }
        
        public function afterSave() {
            parent::afterSave();

            if ($this->idCity != NULL) {
                $treeDistrict = ViewLocation::model()->find(array('condition' => 'idCity =' . $this->idCity));
                if ($treeDistrict != NULL) {
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;
                }
            }
        }        

	public function relations() {
		return array(
			'idDebtor0' => array(self::BELONGS_TO, 'Debtors', 'idDebtor'),
			'idPropertyType0' => array(self::BELONGS_TO, 'PropertyType', 'idPropertyType'),
			'idUserProperty0' => array(self::BELONGS_TO, 'Users', 'idUserProperty'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUserProperty' => Yii::t('front', 'Usuario'),
			'idDebtor' => Yii::t('front', 'Deudor'),
			'idPropertyType' => Yii::t('front', 'Tipo de Bien'),
                        'idCountry' => Yii::t('front', 'País'),
			'idDepartment' => Yii::t('front', 'Departamento'),
                        'idCity' => Yii::t('front', 'Ciudad'),
			'name' => Yii::t('front', 'Nombre'),
                        'address' => Yii::t('front', 'Dirección'),
			'number' => Yii::t('front', '# Matricula'),
			'comment' => Yii::t('app', 'Comentario'),
                        'support' => Yii::t('app', 'Support'),
			'dateCreated' => Yii::t('app', 'Fecha de Creación'),
			'idDebtor0' => null,
			'idPropertyType0' => null,
			'idUserProperty0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUserProperty', $this->idUserProperty);
		$criteria->compare('idDebtor', $this->idDebtor);
                $criteria->compare('idPropertyType', $this->idPropertyType);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('number', $this->number, true);
		$criteria->compare('comment', $this->comment, true);
                $criteria->compare('support', $this->support, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}