<?php

/**
 * This is the model base class for the table "tbl_departments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Departments".
 *
 * Columns in table "tbl_departments" available as properties of the model,
 * followed by relations of table "tbl_departments" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idCountry
 * @property integer $idRegion
 * @property string $name
 * @property string $indicative
 * @property integer $active
 * @property string $dateSave
 *
 * @property Cities[] $cities
 * @property Countries $idCountry0
 * @property Regions $idRegion0
 */
abstract class BaseDepartments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_departments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Departments|Departments', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('idCountry, idRegion, active', 'numerical', 'integerOnly'=>true),
                        array('indicative', 'length', 'max'=>25),
			array('name, dateSave', 'safe'),
			array('idCountry, idRegion, name, indicative, active, dateSave', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idCountry, idRegion, name, indicative, active, dateSave', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cities' => array(self::HAS_MANY, 'Cities', 'idDepartment'),
			'idCountry0' => array(self::BELONGS_TO, 'Countries', 'idCountry'),
			'idRegion0' => array(self::BELONGS_TO, 'Regions', 'idRegion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCountry' => null,
			'idRegion' => null,
			'name' => Yii::t('app', 'Name'),
                        'indicative' => Yii::t('app', 'Indicative'),
			'active' => Yii::t('app', 'Active'),
			'dateSave' => Yii::t('app', 'Date Save'),
			'cities' => null,
			'idCountry0' => null,
			'idRegion0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCountry', $this->idCountry);
		$criteria->compare('idRegion', $this->idRegion);
		$criteria->compare('name', $this->name, true);
                $criteria->compare('indicative', $this->indicative, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateSave', $this->dateSave, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}