<?php

/**
 * This is the model base class for the table "tbl_campaigns_debtors".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CampaignsDebtors".
 *
 * Columns in table "tbl_campaigns_debtors" available as properties of the model,
 * followed by relations of table "tbl_campaigns_debtors" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idCampaigns
 * @property integer $idDebtor
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Campaigns $idCampaigns0
 */
abstract class BaseCampaignsDebtors extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_campaigns_debtors';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CampaignsDebtors|CampaignsDebtors', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('dateCreated', 'required'),
			array('idCampaigns, idDebtor, active', 'numerical', 'integerOnly'=>true),
			array('idCampaigns, idDebtor, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idCampaigns, idDebtor, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCampaigns0' => array(self::BELONGS_TO, 'Campaigns', 'idCampaigns'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCampaigns' => null,
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idCampaigns0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCampaigns', $this->idCampaigns);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}