<?php

/**
 * This is the model base class for the table "tbl_debtors_tasks_support".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsTasksSupport".
 *
 * Columns in table "tbl_debtors_tasks_support" available as properties of the model,
 * followed by relations of table "tbl_debtors_tasks_support" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUserSupport
 * @property integer $idDebtorTask
 * @property string $support
 * @property string $dateCreated
 *
 * @property DebtorsTasks $idDebtorTask0
 * @property Users $idUserSupport0
 */
abstract class BaseDebtorsTasksSupport extends GxActiveRecord {
    
    public $call;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_tasks_support';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsTasksSupport|DebtorsTasksSupports', $n);
	}

	public static function representingColumn() {
		return 'support';
	}
        
        public function getCallInfo(){
            $this->call = null;
            if($this->support != NULL && $this->support != '' && Controller::isJSON($this->support)){                
                $this->call = CJSON::decode($this->support,TRUE);
            }
            return $this->call;
        }

	public function rules() {
		return array(
			array('idUserSupport, idDebtorTask, support', 'required'),
			array('idUserSupport, idDebtorTask', 'numerical', 'integerOnly'=>true),
			array('idUserSupport, idDebtorTask', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUserSupport, idDebtorTask, support, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDebtorTask0' => array(self::BELONGS_TO, 'DebtorsTasks', 'idDebtorTask'),
			'idUserSupport0' => array(self::BELONGS_TO, 'Users', 'idUserSupport'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUserSupport' => null,
			'idDebtorTask' => null,
			'support' => Yii::t('app', 'Support'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idDebtorTask0' => null,
			'idUserSupport0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUserSupport', $this->idUserSupport);
		$criteria->compare('idDebtorTask', $this->idDebtorTask);
		$criteria->compare('support', $this->support, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}