<?php

/**
 * This is the model base class for the table "tbl_metrics_users_profile".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MetricsUsersProfile".
 *
 * Columns in table "tbl_metrics_users_profile" available as properties of the model,
 * followed by relations of table "tbl_metrics_users_profile" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idMetrics
 * @property integer $idUserProfile
 * @property integer $active
 * @property integer $order
 * @property string $dateCreated
 *
 * @property Metrics $idMetrics0
 * @property UsersProfile $idUserProfile0
 */
abstract class BaseMetricsUsersProfile extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_metrics_users_profile';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MetricsUsersProfile|MetricsUsersProfiles', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idUserProfile, order, dateCreated', 'required'),
			array('idMetrics, idUserProfile, active, order', 'numerical', 'integerOnly'=>true),
			array('idMetrics, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idMetrics, idUserProfile, active, order, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idMetrics0' => array(self::BELONGS_TO, 'Metrics', 'idMetrics'),
			'idUserProfile0' => array(self::BELONGS_TO, 'UsersProfile', 'idUserProfile'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idMetrics' => null,
			'idUserProfile' => null,
			'active' => Yii::t('app', 'Active'),
			'order' => Yii::t('app', 'Order'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idMetrics0' => null,
			'idUserProfile0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idMetrics', $this->idMetrics);
		$criteria->compare('idUserProfile', $this->idUserProfile);
		$criteria->compare('active', $this->active);
		$criteria->compare('order', $this->order);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}