<?php

/**
 * This is the model base class for the table "view_debtors_debts".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewDebtorsDebts".
 *
 * Columns in table "view_debtors_debts" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idDebtor
 * @property integer $idState
 * @property integer $idDebtorSubstate
 * @property integer $is_legal
 * @property double $capital
 * @property double $interest
 * @property double $fee
 * @property string $duedate
 * @property string $dayDebt
 *
 */
abstract class BaseViewDebtorsDebts extends GxActiveRecord {

    public $payments;
    public $agreement;
    
    	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_debtors_debts';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewDebtorsDebts|ViewDebtorsDebts', $n);
	}

	public static function representingColumn() {
		return 'duedate';
	}

	public function rules() {
		return array(
			array('id, idDebtor, is_legal', 'required'),
			array('id, idDebtor, idState, idDebtorSubstate, is_legal', 'numerical', 'integerOnly'=>true),
			array('capital, interest, fee', 'numerical'),
			array('dayDebt', 'length', 'max'=>21),
			array('duedate', 'safe'),
			array('idState, idDebtorSubstate, capital, interest, fee, duedate, dayDebt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDebtor, idState, idDebtorSubstate, is_legal, capital, interest, fee, duedate, dayDebt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'idState' => Yii::t('app', 'Id State'),
			'idDebtorSubstate' => Yii::t('app', 'Id Debtor Substate'),
			'is_legal' => Yii::t('app', 'Is Legal'),
			'capital' => Yii::t('app', 'Capital'),
			'interest' => Yii::t('app', 'Interest'),
			'fee' => Yii::t('app', 'Fee'),
			'duedate' => Yii::t('app', 'Duedate'),
			'dayDebt' => Yii::t('app', 'Day Debt'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('idState', $this->idState);
		$criteria->compare('idDebtorSubstate', $this->idDebtorSubstate);
		$criteria->compare('is_legal', $this->is_legal);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('interest', $this->interest);
		$criteria->compare('fee', $this->fee);
		$criteria->compare('duedate', $this->duedate, true);
		$criteria->compare('dayDebt', $this->dayDebt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}