<?php

/**
 * This is the model base class for the table "tbl_type_process".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TypeProcess".
 *
 * Columns in table "tbl_type_process" available as properties of the model,
 * followed by relations of table "tbl_type_process" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $is_legal
 * @property integer $active
 * @property string $dateCreated
 *
 * @property DebtorsDebts[] $debtorsDebts
 */
abstract class BaseTypeProcess extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_type_process';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TypeProcess|TypeProcesses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, dateCreated', 'required'),
			array('is_legal, active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('is_legal, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, is_legal, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'debtorsDebts' => array(self::HAS_MANY, 'DebtorsDebts', 'idTypeProcess'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'is_legal' => Yii::t('app', 'Is Legal'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'debtorsDebts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('is_legal', $this->is_legal);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}