<?php

/**
 * This is the model base class for the table "tbl_metrics".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Metrics".
 *
 * Columns in table "tbl_metrics" available as properties of the model,
 * followed by relations of table "tbl_metrics" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property integer $active
 * @property integer $order
 * @property string $dateCreated
 *
 * @property MetricsUsersProfile[] $metricsUsersProfiles
 */
abstract class BaseMetrics extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_metrics';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Metrics|Metrics', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, alias, order, dateCreated', 'required'),
			array('active, order', 'numerical', 'integerOnly'=>true),
			array('name, alias', 'length', 'max'=>50),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, alias, active, order, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'metricsUsersProfiles' => array(self::HAS_MANY, 'MetricsUsersProfile', 'idMetrics'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'alias' => Yii::t('app', 'Alias'),
			'active' => Yii::t('app', 'Active'),
			'order' => Yii::t('app', 'Order'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'metricsUsersProfiles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('order', $this->order);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}