<?php

/**
 * This is the model base class for the table "view_tendencies".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewTendencies".
 *
 * Columns in table "view_tendencies" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idDebtor
 * @property integer $idDebtorState
 * @property integer $idDebtorSubstate
 * @property double $capital
 * @property double $interest
 * @property double $fee
 * @property double $payments
 * @property double $agreement
 * @property integer $idCity
 * @property integer $ageDebt
 * @property integer $is_legal
 * @property integer $idCustomer
 * @property string $date
 * @property string $dateCreated
 * @property integer $idRegion
 *
 */
abstract class BaseViewTendencies extends GxActiveRecord {

    public $cant;
    public $color;
    
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_tendencies';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewTendencies|ViewTendencies', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('idDebtor, idDebtorState, idDebtorSubstate, capital, interest, fee, payments, agreement, idCity, ageDebt, is_legal, idCustomer, date', 'required'),
			array('id, idDebtor, idDebtorState, idDebtorSubstate, idCity, ageDebt, is_legal, idCustomer, idRegion', 'numerical', 'integerOnly'=>true),
			array('capital, interest, fee, payments, agreement', 'numerical'),
			array('dateCreated', 'safe'),
			array('id, dateCreated, idRegion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDebtor, idDebtorState, idDebtorSubstate, capital, interest, fee, payments, agreement, idCity, ageDebt, is_legal, idCustomer, date, dateCreated, idRegion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'idDebtorState' => Yii::t('app', 'Id Debtor State'),
			'idDebtorSubstate' => Yii::t('app', 'Id Debtor Substate'),
			'capital' => Yii::t('app', 'Capital'),
			'interest' => Yii::t('app', 'Interest'),
			'fee' => Yii::t('app', 'Fee'),
			'payments' => Yii::t('app', 'Payments'),
			'agreement' => Yii::t('app', 'Agreement'),
			'idCity' => Yii::t('app', 'Id City'),
			'ageDebt' => Yii::t('app', 'Age Debt'),
			'is_legal' => Yii::t('app', 'Is Legal'),
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'date' => Yii::t('app', 'Date'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idRegion' => Yii::t('app', 'Id Region'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('idDebtorState', $this->idDebtorState);
		$criteria->compare('idDebtorSubstate', $this->idDebtorSubstate);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('interest', $this->interest);
		$criteria->compare('fee', $this->fee);
		$criteria->compare('payments', $this->payments);
		$criteria->compare('agreement', $this->agreement);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('ageDebt', $this->ageDebt);
		$criteria->compare('is_legal', $this->is_legal);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);
		$criteria->compare('idRegion', $this->idRegion);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}