<?php

/**
 * This is the model base class for the table "tbl_campaigns".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Campaigns".
 *
 * Columns in table "tbl_campaigns" available as properties of the model,
 * followed by relations of table "tbl_campaigns" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idCustomer
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Users $idCustomer0
 * @property CampaignsCoordinators[] $campaignsCoordinators
 * @property CampaignsDebtors[] $campaignsDebtors
 * @property ReferralsCampaigns[] $referralsCampaigns
 */
abstract class BaseCampaigns extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_campaigns';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Campaigns|Campaigns', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('dateCreated', 'required'),
			array('idCustomer, active', 'numerical', 'integerOnly'=>true),
			array('idCustomer, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idCustomer, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCustomer0' => array(self::BELONGS_TO, 'Users', 'idCustomer'),
			'campaignsCoordinators' => array(self::HAS_MANY, 'CampaignsCoordinators', 'idCampaign'),
			'campaignsDebtors' => array(self::HAS_MANY, 'CampaignsDebtors', 'idCampaigns'),
			'referralsCampaigns' => array(self::HAS_MANY, 'ReferralsCampaigns', 'idCampaigns'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCustomer' => null,
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idCustomer0' => null,
			'campaignsCoordinators' => null,
			'campaignsDebtors' => null,
			'referralsCampaigns' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}