<?php

/**
 * This is the model base class for the table "view_indicators_property".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewIndicatorsProperty".
 *
 * Columns in table "view_indicators_property" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idCustomer
 * @property integer $idRegion
 * @property integer $ageDebt
 * @property string $idState
 * @property double $capital
 * @property integer $idDebtor
 * @property string $cant
 *
 */
abstract class BaseViewIndicatorsProperty extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_indicators_property';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewIndicatorsProperty|ViewIndicatorsProperties', $n);
	}

	public static function representingColumn() {
		return 'idState';
	}

	public function rules() {
		return array(
			array('idCustomer, idRegion, ageDebt, idDebtor', 'numerical', 'integerOnly'=>true),
			array('capital', 'numerical'),
			array('idState', 'length', 'max'=>255),
			array('cant', 'length', 'max'=>21),
			array('idCustomer, idRegion, ageDebt, idState, capital, idDebtor, cant', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idCustomer, idRegion, ageDebt, idState, capital, idDebtor, cant', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'idRegion' => Yii::t('app', 'Id Region'),
			'ageDebt' => Yii::t('app', 'Age Debt'),
			'idState' => Yii::t('app', 'Id State'),
			'capital' => Yii::t('app', 'Capital'),
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'cant' => Yii::t('app', 'Cant'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('idRegion', $this->idRegion);
		$criteria->compare('ageDebt', $this->ageDebt);
		$criteria->compare('idState', $this->idState, true);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('cant', $this->cant, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}