<?php

/**
 * This is the model base class for the table "tbl_tempo_assignments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TempoAssignments".
 *
 * Columns in table "tbl_tempo_assignments" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idCustomer
 * @property integer $idUserImport
 * @property integer $idDebtor
 * @property integer $migrate
 * @property string $code
 * @property string $name
 * @property string $dateCreated
 *
 */
abstract class BaseTempoAssignments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tempo_assignments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TempoAssignments|TempoAssignments', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, name, dateCreated', 'required'),
			array('idCustomer, idUserImport, idDebtor, migrate', 'numerical', 'integerOnly'=>true),
			array('idCustomer, idUserImport, idDebtor, migrate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idCustomer, idUserImport, idDebtor, migrate, code, name, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'idUserImport' => Yii::t('app', 'Id User Import'),
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'migrate' => Yii::t('app', 'Migrate'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('idUserImport', $this->idUserImport);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('migrate', $this->migrate);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}