<?php

/**
 * This is the model base class for the table "tbl_suggestions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Suggestions".
 *
 * Columns in table "tbl_suggestions" available as properties of the model,
 * followed by relations of table "tbl_suggestions" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idCreator
 * @property integer $idSuggestion
 * @property string $title
 * @property string $comments
 * @property string $support
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Users $idCreator0
 */
abstract class BaseSuggestions extends GxActiveRecord {
    
    public $profile;
    public $name;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_suggestions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Suggestions|Suggestions', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, comments', 'required'),
			array('idCreator, idSuggestion, active', 'numerical', 'integerOnly'=>true),
                        array('support', 'match', 'pattern'=>'/\.(gif|jpg|jpeg|png|pdf|tiff)$/i','message'=>Yii::t('err','El {attribute} es inválido, Solo los archivos con estas extensiones son permitidos: gif, jpg, jpeg, png, tiff, pdf'), 'allowEmpty'=>true, 'on' => 'support'),
			array('title', 'length', 'max'=>200),
			array('idCreator, idSuggestion, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('profile, name', 'safe'),
			array('id, idCreator, idSuggestion, title, comments, support, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCreator0' => array(self::BELONGS_TO, 'Users', 'idCreator'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCreator' => null,
			'idSuggestion' => Yii::t('app', 'Id Suggestion'),
			'title' => Yii::t('app', 'Tipo'),
			'comments' => Yii::t('app', 'Comentarios'),
			'support' => Yii::t('app', 'Soporte'),
			'active' => Yii::t('app', 'Activo'),
			'dateCreated' => Yii::t('app', 'Fecha de Creación'),
			'idCreator0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCreator', $this->idCreator);
		$criteria->compare('idSuggestion', $this->idSuggestion);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('comments', $this->comments, true);
		$criteria->compare('support', $this->support, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}