<?php

/**
 * This is the model base class for the table "tbl_coordinator_adviser".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CoordinatorAdviser".
 *
 * Columns in table "tbl_coordinator_adviser" available as properties of the model,
 * followed by relations of table "tbl_coordinator_adviser" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idCoordinator
 * @property integer $idAdviser
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Users $idCoordinator0
 * @property Users $idAdviser0
 */
abstract class BaseCoordinatorAdviser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_coordinator_adviser';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CoordinatorAdviser|CoordinatorAdvisers', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idCoordinator, idAdviser,', 'required'),
			array('idCoordinator, idAdviser, active', 'numerical', 'integerOnly'=>true),
			array('idCoordinator, idAdviser, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idCoordinator, idAdviser, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCoordinator0' => array(self::BELONGS_TO, 'Users', 'idCoordinator'),
			'idAdviser0' => array(self::BELONGS_TO, 'Users', 'idAdviser'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCoordinator' => Yii::t('front', 'Coordinador'),
			'idAdviser' => Yii::t('front', 'Asesor'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('front', 'Fecha de Creación'),
			'idCoordinator0' => null,
			'idAdviser0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCoordinator', $this->idCoordinator);
		$criteria->compare('idAdviser', $this->idAdviser);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}