<?php

/**
 * This is the model base class for the table "tbl_age_debt".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AgeDebt".
 *
 * Columns in table "tbl_age_debt" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $ageFrom
 * @property integer $ageTo
 * @property string $text
 * @property string $dateCreated
 *
 */
abstract class BaseAgeDebt extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_age_debt';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AgeDebt|AgeDebts', $n);
	}

	public static function representingColumn() {
		return 'text';
	}

	public function rules() {
		return array(
			array('ageFrom, ageTo, text, dateCreated', 'required'),
			array('ageFrom, ageTo', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>500),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, ageFrom, ageTo, text, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'ageFrom' => Yii::t('app', 'Age From'),
			'ageTo' => Yii::t('app', 'Age To'),
			'text' => Yii::t('app', 'Text'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('ageFrom', $this->ageFrom);
		$criteria->compare('ageTo', $this->ageTo);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}