<?php

/**
 * This is the model base class for the table "tbl_investment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Investment".
 *
 * Columns in table "tbl_investment" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $lot
 * @property integer $value
 * @property string $dateCreated
 *
 */
abstract class BaseInvestment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_investment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Investment|Investments', $n);
	}

	public static function representingColumn() {
		return 'lot';
	}

	public function rules() {
		return array(
			array('lot, dateCreated', 'required'),
			array('value', 'numerical', 'integerOnly'=>true),
			array('lot', 'length', 'max'=>50),
			array('value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('lot, value, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'lot' => Yii::t('app', 'Lot'),
			'value' => Yii::t('app', 'Value'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('lot', $this->lot, true);
		$criteria->compare('value', $this->value);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}