<?php

/**
 * This is the model base class for the table "tbl_referrals".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Referrals".
 *
 * Columns in table "tbl_referrals" available as properties of the model,
 * followed by relations of table "tbl_referrals" available as properties of the model.
 *
 * @property integer $id
 * @property string $excel
 * @property string $date
 * @property string $code
 * @property integer $idCustomer
 * @property integer $active
 * @property string $descripcion
 * @property integer $idOrderService
 *
 * @property ReferralsCampaigns[] $referralsCampaigns
 */
abstract class BaseReferrals extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_referrals';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Referrals|Referrals', $n);
	}

	public static function representingColumn() {
		return 'excel';
	}

	public function rules() {
		return array(
			array('idCustomer, active, idOrderService', 'numerical', 'integerOnly'=>true),
			array('excel, date, code, descripcion', 'safe'),
			array('excel, date, code, idCustomer, active, descripcion, idOrderService', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, excel, date, code, idCustomer, active, descripcion, idOrderService', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'referralsCampaigns' => array(self::HAS_MANY, 'ReferralsCampaigns', 'idReferrals'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'excel' => Yii::t('app', 'Excel'),
			'date' => Yii::t('app', 'Date'),
			'code' => Yii::t('app', 'Code'),
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'active' => Yii::t('app', 'Active'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'idOrderService' => Yii::t('app', 'Id Order Service'),
			'referralsCampaigns' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('excel', $this->excel, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('active', $this->active);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('idOrderService', $this->idOrderService);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}