<?php

/**
 * This is the model base class for the table "tbl_users_sessions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersSessions".
 *
 * Columns in table "tbl_users_sessions" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idUser
 * @property string $data
 * @property integer $expire
 *
 */
abstract class BaseUsersSessions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_users_sessions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersSessions|UsersSessions', $n);
	}

	public static function representingColumn() {
		return 'data';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, idUser, expire', 'numerical', 'integerOnly'=>true),
			array('data', 'safe'),
			array('idUser, data, expire', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUser, data, expire', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUser' => Yii::t('app', 'Id User'),
			'data' => Yii::t('app', 'Data'),
			'expire' => Yii::t('app', 'Expire'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUser', $this->idUser);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('expire', $this->expire);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}