<?php

/**
 * This is the model base class for the table "view_licenses".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewLicenses".
 *
 * Columns in table "view_licenses" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $numberDocument
 * @property double $capital
 * @property integer $idCity
 * @property string $city
 * @property integer $idPlan
 * @property string $plan
 * @property string $users
 * @property integer $active
 *
 */
abstract class BaseViewLicenses extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_licenses';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewLicenses|ViewLicenses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id, idCity, idPlan, active', 'numerical', 'integerOnly'=>true),
			array('capital', 'numerical'),
			array('plan', 'length', 'max'=>50),
			array('users', 'length', 'max'=>21),
			array('name, numberDocument, city', 'safe'),
			array('id, name, numberDocument, capital, idCity, city, idPlan, plan, users, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, numberDocument, capital, idCity, city, idPlan, plan, users, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'numberDocument' => Yii::t('app', 'Number Document'),
			'capital' => Yii::t('app', 'Capital'),
			'idCity' => Yii::t('app', 'Id City'),
			'city' => Yii::t('app', 'City'),
			'idPlan' => Yii::t('app', 'Id Plan'),
			'plan' => Yii::t('app', 'Plan'),
			'users' => Yii::t('app', 'Users'),
			'active' => Yii::t('app', 'Active'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('numberDocument', $this->numberDocument, true);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('idPlan', $this->idPlan);
		$criteria->compare('plan', $this->plan, true);
		$criteria->compare('users', $this->users, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}