<?php

/**
 * This is the model base class for the table "tbl_type_documents".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TypeDocuments".
 *
 * Columns in table "tbl_type_documents" available as properties of the model,
 * followed by relations of table "tbl_type_documents" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $name_complete
 * @property string $alias
 * @property string $dateCreated
 *
 * @property Users[] $users
 */
abstract class BaseTypeDocuments extends GxActiveRecord {
    
    public $capital;
    public $cant;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_type_documents';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TypeDocuments|TypeDocuments', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, name_complete, dateCreated', 'required'),
			array('name, name_complete, alias', 'length', 'max'=>50),
			array('alias', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, name_complete, alias, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'users' => array(self::HAS_MANY, 'Users', 'idTypeDocument'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'name_complete' => Yii::t('app', 'Name Complete'),
			'alias' => Yii::t('app', 'Alias'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'users' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('name_complete', $this->name_complete, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}