<?php

/**
 * This is the model base class for the table "tbl_type_products".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TypeProducts".
 *
 * Columns in table "tbl_type_products" available as properties of the model,
 * followed by relations of table "tbl_type_products" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $dateCreated
 *
 * @property DebtorsObligations[] $debtorsObligations
 */
abstract class BaseTypeProducts extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_type_products';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TypeProducts|TypeProducts', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, dateCreated', 'required'),
			array('name', 'length', 'max'=>50),
			array('id, name, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'debtorsObligations' => array(self::HAS_MANY, 'DebtorsObligations', 'idTypeProduct'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'debtorsObligations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}