<?php

/**
 * This is the model base class for the table "tbl_referrals_campaigns".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ReferralsCampaigns".
 *
 * Columns in table "tbl_referrals_campaigns" available as properties of the model,
 * followed by relations of table "tbl_referrals_campaigns" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idReferrals
 * @property integer $idCustomer
 * @property integer $idCampaigns
 * @property integer $active
 * @property string $dateSave
 *
 * @property Campaigns $idCampaigns0
 * @property Users $idCustomer0
 * @property Referrals $idReferrals0
 */
abstract class BaseReferralsCampaigns extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_referrals_campaigns';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ReferralsCampaigns|ReferralsCampaigns', $n);
	}

	public static function representingColumn() {
		return 'dateSave';
	}

	public function rules() {
		return array(
			array('idReferrals, idCustomer, idCampaigns, active', 'numerical', 'integerOnly'=>true),
			array('dateSave', 'safe'),
			array('idReferrals, idCustomer, idCampaigns, active, dateSave', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idReferrals, idCustomer, idCampaigns, active, dateSave', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCampaigns0' => array(self::BELONGS_TO, 'Campaigns', 'idCampaigns'),
			'idCustomer0' => array(self::BELONGS_TO, 'Users', 'idCustomer'),
			'idReferrals0' => array(self::BELONGS_TO, 'Referrals', 'idReferrals'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idReferrals' => null,
			'idCustomer' => null,
			'idCampaigns' => null,
			'active' => Yii::t('app', 'Active'),
			'dateSave' => Yii::t('app', 'Date Save'),
			'idCampaigns0' => null,
			'idCustomer0' => null,
			'idReferrals0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idReferrals', $this->idReferrals);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('idCampaigns', $this->idCampaigns);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateSave', $this->dateSave, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}