<?php

/**
 * This is the model base class for the table "tbl_debtors_contacts".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsContacts".
 *
 * Columns in table "tbl_debtors_contacts" available as properties of the model,
 * followed by relations of table "tbl_debtors_contacts" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUserCreated
 * @property integer $idDebtor
 * @property integer $idTypeDebtorContact
 * @property integer $idCity
 * @property string $name
 * @property string $code
 * @property string $email
 * @property string $address
 * @property string $neighborhood
 * @property string $phone
 * @property string $mobile
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Cities $idCity0
 * @property Debtors $idDebtor0
 * @property Users $idUserCreated0
 * @property TypeDebtorContact $idTypeDebtorContact0
 * @property DebtorsContactsDemographics[] $debtorsContactsDemographics
 */
abstract class BaseDebtorsContacts extends GxActiveRecord {
    
        public $idCountry;
        public $idDepartment;
        public $fullDistrict;
        public $state;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_contacts';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsContacts|DebtorsContacts', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}
        
         public function afterFind(){
            parent::afterFind();                        
            
            if($this->idCity!= NULL){
                $treeDistrict = ViewLocation::model()->find(array('condition' =>'idCity ='.$this->idCity));
                if($treeDistrict != NULL){
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;                    
                }                
            } 
            
            $this->state = Yii::t('front', 'Por validar');
            if($this->active == 1){
                $this->state = Yii::t('front', 'Localizado');                
            }elseif($this->active == 2){
                $this->state = Yii::t('front', 'Ilocalizado');
            }
        }
        
        public function afterSave() {
            parent::afterSave();
            
            if($this->idCity!= NULL){
                $treeDistrict = ViewLocation::model()->find(array('condition' =>'idCity ='.$this->idCity));
                if($treeDistrict != NULL){
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;                    
                }                
            } 
            
            $this->state = Yii::t('front', 'Por validar');
            if($this->active == 1){
                $this->state = Yii::t('front', 'Localizado');                
            }elseif($this->active == 2){
                $this->state = Yii::t('front', 'Ilocalizado');
            }
        }

	public function rules() {
		return array(
			array('name, code, idCountry, idDepartment, idCity, email, phone, mobile, address', 'required'),
			array('idUserCreated, idDebtor, idTypeDebtorContact, idCity, active', 'numerical', 'integerOnly'=>true),
			array('name, address, phone, mobile', 'length', 'max'=>500),
                        array('email','email'),
                        array('phone','match', 'pattern' => '/^[1-9]\d{6}$/','message' => '{attribute} inválido'),  
                        array('mobile','match', 'pattern' => '/^3[\d]{9}$/','message' => '{attribute} inválido'),
			array('code, email, neighborhood', 'safe'),
			array('idUserCreated, idDebtor, idTypeDebtorContact, idCity, name, code, email, address, neighborhood, phone, mobile, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUserCreated, idDebtor, idTypeDebtorContact, idCity, name, code, email, address, neighborhood, phone, mobile, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCity0' => array(self::BELONGS_TO, 'Cities', 'idCity'),
			'idDebtor0' => array(self::BELONGS_TO, 'Debtors', 'idDebtor'),
			'idUserCreated0' => array(self::BELONGS_TO, 'Users', 'idUserCreated'),
			'idTypeDebtorContact0' => array(self::BELONGS_TO, 'TypeDebtorContact', 'idTypeDebtorContact'),
			'debtorsContactsDemographics' => array(self::HAS_MANY, 'DebtorsContactsDemographics', 'idDebtorContact'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUserCreated' => null,
			'idDebtor' => null,
			'idTypeDebtorContact' => null,
                        'idCountry' => Yii::t('front', 'País'),
			'idDepartment' => Yii::t('front', 'Departamento'),
			'idCity' => Yii::t('front', 'Ciudad'),
			'name' => Yii::t('app', 'Nombre'),
			'code' => Yii::t('app', 'Identificación'),
			'email' => Yii::t('app', 'Email'),
			'address' => Yii::t('app', 'Dirección'),
			'neighborhood' => Yii::t('app', 'Barrio'),
			'phone' => Yii::t('app', 'Teléfono'),
			'mobile' => Yii::t('app', 'Celular'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Fecha de Creación'),
			'idCity0' => null,
			'idDebtor0' => null,
			'idUserCreated0' => null,
			'idTypeDebtorContact0' => null,
			'debtorsContactsDemographics' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUserCreated', $this->idUserCreated);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('idTypeDebtorContact', $this->idTypeDebtorContact);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('neighborhood', $this->neighborhood, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('mobile', $this->mobile, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}