<?php

/**
 * This is the model base class for the table "view_debtors_check_demographics".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewDebtorsCheckDemographics".
 *
 * Columns in table "view_debtors_check_demographics" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idDebtor
 * @property integer $cant
 *
 */
abstract class BaseViewDebtorsCheckDemographics extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_debtors_check_demographics';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewDebtorsCheckDemographics|ViewDebtorsCheckDemographics', $n);
	}

	public static function representingColumn() {
		return 'idDebtor';
	}

	public function rules() {
		return array(
			array('idDebtor, cant', 'numerical', 'integerOnly'=>true),
			array('idDebtor, cant', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idDebtor, cant', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'cant' => Yii::t('app', 'Cant'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('cant', $this->cant);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}