<?php

/**
 * This is the model base class for the table "view_debtors_emails".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewDebtorsEmails".
 *
 * Columns in table "view_debtors_emails" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idDebtor
 * @property string $email
 *
 */
abstract class BaseViewDebtorsEmails extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_debtors_emails';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewDebtorsEmails|ViewDebtorsEmails', $n);
	}

	public static function representingColumn() {
		return 'email';
	}

	public function rules() {
		return array(
			array('idDebtor', 'numerical', 'integerOnly'=>true),
			array('email', 'safe'),
			array('idDebtor, email', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idDebtor, email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'email' => Yii::t('app', 'Email'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('email', $this->email, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}