<?php

/**
 * This is the model base class for the table "tbl_users_profiles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersProfiles".
 *
 * Columns in table "tbl_users_profiles" available as properties of the model,
 * followed by relations of table "tbl_users_profiles" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUser
 * @property integer $idUserProfile
 * @property integer $active
 * @property integer $is_internal
 * @property string $dateCreated
 *
 * @property UsersProfile $idUserProfile0
 * @property Users $idUser0
 */
abstract class BaseUsersProfiles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_users_profiles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersProfiles|UsersProfiles', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idUser, idUserProfile', 'required'),
			array('idUser, idUserProfile, active, is_internal', 'numerical', 'integerOnly'=>true),
			array('idUser, idUserProfile, active, is_internal', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUser, idUserProfile, active, is_internal, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUserProfile0' => array(self::BELONGS_TO, 'UsersProfile', 'idUserProfile'),
			'idUser0' => array(self::BELONGS_TO, 'Users', 'idUser'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUser' => null,
			'idUserProfile' => null,
			'active' => Yii::t('app', 'Active'),
                        'is_internal' => Yii::t('app', 'Is Internal'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idUserProfile0' => null,
			'idUser0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUser', $this->idUser);
		$criteria->compare('idUserProfile', $this->idUserProfile);
		$criteria->compare('active', $this->active);
                $criteria->compare('is_internal', $this->is_internal);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}