<?php

/**
 * This is the model base class for the table "tbl_office_legal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OfficeLegal".
 *
 * Columns in table "tbl_office_legal" available as properties of the model,
 * followed by relations of table "tbl_office_legal" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idOfficeLegal
 * @property integer $type
 * @property string $name
 * @property integer $active
 * @property string $dateCreated
 *
 * @property DebtorsDebts[] $debtorsDebts
 * @property DebtorsDebts[] $debtorsDebts1
 * @property DebtorsObligations[] $debtorsObligations
 * @property DebtorsObligations[] $debtorsObligations1
 * @property OfficeLegal $idOfficeLegal0
 * @property OfficeLegal[] $officeLegals
 */
abstract class BaseOfficeLegal extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_office_legal';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OfficeLegal|OfficeLegals', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, active, dateCreated', 'required'),
			array('idOfficeLegal, type, active', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>500),
			array('idOfficeLegal, type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idOfficeLegal, type, name, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'debtorsDebts' => array(self::HAS_MANY, 'DebtorsDebts', 'idOfficeLegal'),
			'debtorsDebts1' => array(self::HAS_MANY, 'DebtorsDebts', 'idCategoryLegal'),
			'debtorsObligations' => array(self::HAS_MANY, 'DebtorsObligations', 'idOfficeLegal'),
			'debtorsObligations1' => array(self::HAS_MANY, 'DebtorsObligations', 'idCategoryLegal'),
			'idOfficeLegal0' => array(self::BELONGS_TO, 'OfficeLegal', 'idOfficeLegal'),
			'officeLegals' => array(self::HAS_MANY, 'OfficeLegal', 'idOfficeLegal'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idOfficeLegal' => null,
			'type' => Yii::t('app', 'Type'),
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'debtorsDebts' => null,
			'debtorsDebts1' => null,
			'debtorsObligations' => null,
			'debtorsObligations1' => null,
			'idOfficeLegal0' => null,
			'officeLegals' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idOfficeLegal', $this->idOfficeLegal);
		$criteria->compare('type', $this->type);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}