<?php

/**
 * This is the model base class for the table "view_debtors_legal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewDebtorsLegal".
 *
 * Columns in table "view_debtors_legal" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idDebtor
 * @property integer $idCustomer
 * @property integer $idCity
 * @property integer $idState
 * @property integer $idDebtorState
 * @property string $customer
 * @property string $name
 * @property string $code
 * @property double $capital
 * @property string $duedate
 * @property string $prescription
 * @property integer $ageDebt
 * @property string $dayDebt
 * @property string $city
 *
 */
abstract class BaseViewDebtorsLegal extends GxActiveRecord {

    public $cant;
    public $date;
    
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_debtors_legal';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewDebtorsLegal|ViewDebtorsLegals', $n);
	}

	public static function representingColumn() {
		return 'customer';
	}

	public function rules() {
		return array(
			array('id, idDebtor, idCustomer, idCity, idState, idDebtorState, ageDebt', 'numerical', 'integerOnly'=>true),
			array('capital', 'numerical'),
			array('dayDebt', 'length', 'max'=>21),
			array('customer, name, code, duedate, prescription, city', 'safe'),
			array('id, idDebtor, idCustomer, idCity, idState, idDebtorState, customer, name, code, capital, duedate, prescription, ageDebt, dayDebt, city', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDebtor, idCustomer, idCity, idState, idDebtorState, customer, name, code, capital, duedate, prescription, ageDebt, dayDebt, city', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'idCity' => Yii::t('app', 'Id City'),
			'idState' => Yii::t('app', 'Id State'),
			'idDebtorState' => Yii::t('app', 'Id Debtor State'),
			'customer' => Yii::t('app', 'Customer'),
			'name' => Yii::t('app', 'Name'),
			'code' => Yii::t('app', 'Code'),
			'capital' => Yii::t('app', 'Capital'),
			'duedate' => Yii::t('app', 'Duedate'),
			'prescription' => Yii::t('app', 'Prescription'),
			'ageDebt' => Yii::t('app', 'Age Debt'),
			'dayDebt' => Yii::t('app', 'Day Debt'),
			'city' => Yii::t('app', 'City'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('idState', $this->idState);
		$criteria->compare('idDebtorState', $this->idDebtorState);
		$criteria->compare('customer', $this->customer, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('duedate', $this->duedate, true);
		$criteria->compare('prescription', $this->prescription, true);
		$criteria->compare('ageDebt', $this->ageDebt);
		$criteria->compare('dayDebt', $this->dayDebt, true);
		$criteria->compare('city', $this->city, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}