<?php

/**
 * This is the model base class for the table "tbl_debtors_obligations_predictions_agreement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsObligationsPredictionsAgreement".
 *
 * Columns in table "tbl_debtors_obligations_predictions_agreement" available as properties of the model,
 * followed by relations of table "tbl_debtors_obligations_predictions_agreement" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idMLModel
 * @property integer $idDebtorObligation
 * @property double $probabilityTrue
 * @property string $dateCreated
 *
 * @property DebtorsObligations $idDebtorObligation0
 * @property Mlmodels $idMLModel0
 */
abstract class BaseDebtorsObligationsPredictionsAgreement extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_obligations_predictions_agreement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsObligationsPredictionsAgreement|DebtorsObligationsPredictionsAgreements', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idMLModel, idDebtorObligation, probabilityTrue, dateCreated', 'required'),
			array('idMLModel, idDebtorObligation', 'numerical', 'integerOnly'=>true),
			array('probabilityTrue', 'numerical'),
			array('id, idMLModel, idDebtorObligation, probabilityTrue, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDebtorObligation0' => array(self::BELONGS_TO, 'DebtorsObligations', 'idDebtorObligation'),
			'idMLModel0' => array(self::BELONGS_TO, 'Mlmodels', 'idMLModel'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idMLModel' => null,
			'idDebtorObligation' => null,
			'probabilityTrue' => Yii::t('app', 'Probability True'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idDebtorObligation0' => null,
			'idMLModel0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idMLModel', $this->idMLModel);
		$criteria->compare('idDebtorObligation', $this->idDebtorObligation);
		$criteria->compare('probabilityTrue', $this->probabilityTrue);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}