<?php

/**
 * This is the model base class for the table "tbl_debtors_co_signer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsCoSigner".
 *
 * Columns in table "tbl_debtors_co_signer" available as properties of the model,
 * followed by relations of table "tbl_debtors_co_signer" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUserCoSigner
 * @property integer $idDebtor
 * @property integer $idCity
 * @property string $name
 * @property string $email
 * @property string $address
 * @property string $phone
 * @property string $comment
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Cities $idCity0
 * @property Debtors $idDebtor0
 * @property Users $idUserCoSigner0
 */
abstract class BaseDebtorsCoSigner extends GxActiveRecord {
    
    public $idCountry;
    public $idDepartment;
    public $fullDistrict;
    public $state;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_co_signer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsCoSigner|DebtorsCoSigners', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idUserCoSigner, idDebtor, idCountry, idDepartment, idCity, name, address, phone, email, active', 'required'),
			array('idUserCoSigner, idDebtor, idCity, active', 'numerical', 'integerOnly'=>true),
			array('name, address, phone', 'length', 'max'=>500),
			array('email, comment', 'safe'),
                        array('phone','match', 'pattern' => '/^[1-9]\d{6}$/','message' => '{attribute} inválido'),
			array('idUserCoSigner, idDebtor, idCity, name, email, address, phone, comment, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUserCoSigner, idDebtor, idCountry, idDepartment, idCity, name, email, address, phone, comment, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}
        
        public function afterFind(){
            parent::afterFind();                        
            
            if($this->idCity!= NULL){
                $treeDistrict = ViewLocation::model()->find(array('condition' =>'idCity ='.$this->idCity));
                if($treeDistrict != NULL){
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;                    
                }                
            } 
                        
            $this->state = Yii::t('front', 'Por validar');
            if($this->active == 1){
                $this->state = Yii::t('front', 'Localizado');                
            }elseif($this->active == 2){
                $this->state = Yii::t('front', 'Ilocalizado');
            }
        }
        
        public function afterSave() {
            parent::afterSave();
            
            if($this->idCity!= NULL){
                $treeDistrict = ViewLocation::model()->find(array('condition' =>'idCity ='.$this->idCity));
                if($treeDistrict != NULL){
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;                    
                }                
            } 
                                    
            $this->state = Yii::t('front', 'Por validar');
            if($this->active == 1){
                $this->state = Yii::t('front', 'Localizado');                
            }elseif($this->active == 2){
                $this->state = Yii::t('front', 'Ilocalizado');
            }
        }

	public function relations() {
		return array(
			'idCity0' => array(self::BELONGS_TO, 'Cities', 'idCity'),
			'idDebtor0' => array(self::BELONGS_TO, 'Debtors', 'idDebtor'),
			'idUserCoSigner0' => array(self::BELONGS_TO, 'Users', 'idUserCoSigner'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUserCoSigner' => Yii::t('front', 'Creador'),
			'idDebtor' => Yii::t('front', 'Deudor'),
                        'idCountry' => Yii::t('front', 'País'),
			'idDepartment' => Yii::t('front', 'Departamento'),
			'idCity' => Yii::t('front', 'Ciudad'),
			'name' => Yii::t('front', 'Nombre'),
			'email' => Yii::t('front', 'Email'),
			'address' => Yii::t('front', 'Dirección'),
			'phone' => Yii::t('front', 'Teléfono'),
			'comment' => Yii::t('front', 'Comentario'),
			'active' => Yii::t('front', 'Estado'),
			'dateCreated' => Yii::t('front', 'Fecha de Creación'),
			'idCity0' => null,
			'idDebtor0' => null,
			'idUserCoSigner0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUserCoSigner', $this->idUserCoSigner);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}