<?php

/**
 * This is the model base class for the table "tbl_payments_whopaid".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PaymentsWhopaid".
 *
 * Columns in table "tbl_payments_whopaid" available as properties of the model,
 * followed by relations of table "tbl_payments_whopaid" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $active
 *
 * @property DebtorsPayments[] $debtorsPayments
 */
abstract class BasePaymentsWhopaid extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_payments_whopaid';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PaymentsWhopaid|PaymentsWhopaids', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('active', 'numerical', 'integerOnly'=>true),
			array('name', 'safe'),
			array('name, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'debtorsPayments' => array(self::HAS_MANY, 'DebtorsPayments', 'idPaymentsWhoPaid'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'debtorsPayments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}