<?php

/**
 * This is the model base class for the table "tbl_clusters".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Clusters".
 *
 * Columns in table "tbl_clusters" available as properties of the model,
 * followed by relations of table "tbl_clusters" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idMLModel
 * @property string $clusterCode
 * @property string $name
 * @property string $description
 * @property string $tags
 * @property string $json_detail
 * @property string $dateCreated
 *
 * @property Mlmodels $idMLModel0
 * @property DebtorsObligationsClusters[] $debtorsObligationsClusters
 */
abstract class BaseClusters extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_clusters';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Clusters|Clusters', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idMLModel', 'required'),
			array('idMLModel', 'numerical', 'integerOnly'=>true),
			array('clusterCode, name, description, tags', 'length', 'max'=>500),
                        array('json_detail', 'safe'),
			array('clusterCode, name, description, tags, json_detail', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idMLModel, clusterCode, name, description, tags, json_detail, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idMLModel0' => array(self::BELONGS_TO, 'Mlmodels', 'idMLModel'),
                        'debtorsObligationsClusters' => array(self::HAS_MANY, 'DebtorsObligationsClusters', 'idCluster'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idMLModel' => null,
			'clusterCode' => Yii::t('app', 'Cluster Code'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'tags' => Yii::t('app', 'Tags'),
                        'json_detail' => Yii::t('app', 'Json Detail'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idMLModel0' => null,
                        'debtorsObligationsClusters' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idMLModel', $this->idMLModel);
		$criteria->compare('clusterCode', $this->clusterCode, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('tags', $this->tags, true);
                $criteria->compare('json_detail', $this->json_detail, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}