<?php

/**
 * This is the model base class for the table "tbl_users_state".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersState".
 *
 * Columns in table "tbl_users_state" available as properties of the model,
 * followed by relations of table "tbl_users_state" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $active
 * @property integer $type
 * @property string $dateCreated
 *
 * @property UsersBusiness[] $usersBusinesses
 * @property UsersBusinessTasks[] $usersBusinessTasks
 */
abstract class BaseUsersState extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_users_state';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersState|UsersStates', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('dateCreated', 'required'),
			array('active, type', 'numerical', 'integerOnly'=>true),
			array('name', 'safe'),
			array('name, active, type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, active, type, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usersBusinesses' => array(self::HAS_MANY, 'UsersBusiness', 'idUserState'),
			'usersBusinessTasks' => array(self::HAS_MANY, 'UsersBusinessTasks', 'idUserState'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'type' => Yii::t('app', 'Type'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'usersBusinesses' => null,
			'usersBusinessTasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('type', $this->type);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}