<?php

/**
 * This is the model base class for the table "view_management_last".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewManagementLast".
 *
 * Columns in table "view_management_last" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idDebtorDebt
 * @property string $date
 *
 */
abstract class BaseViewManagementLast extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_management_last';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewManagementLast|ViewManagementLasts', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('idDebtorDebt', 'numerical', 'integerOnly'=>true),
			array('date', 'safe'),
			array('idDebtorDebt, date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idDebtorDebt, date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idDebtorDebt' => Yii::t('app', 'Id Debtor Debt'),
			'date' => Yii::t('app', 'Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idDebtorDebt', $this->idDebtorDebt);
		$criteria->compare('date', $this->date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}