<?php

/**
 * This is the model base class for the table "view_maps".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewMaps".
 *
 * Columns in table "view_maps" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idCustomer
 * @property string $code
 * @property string $name
 * @property integer $ageDebt
 * @property integer $idRegion
 * @property string $idState
 * @property string $address
 * @property string $lat
 * @property string $lng
 *
 */
abstract class BaseViewMaps extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_maps';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewMaps|ViewMaps', $n);
	}

	public static function representingColumn() {
		return 'idState';
	}

	public function rules() {
		return array(
			array('id, idCustomer, ageDebt, idRegion', 'numerical', 'integerOnly'=>true),
			array('idState', 'length', 'max'=>255),
			array('code, name, address, lat, lng', 'safe'),
			array('id, idCustomer, code, name, ageDebt, idRegion, idState, address, lat, lng', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idCustomer, code, name, ageDebt, idRegion, idState, address, lat, lng', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'code' => Yii::t('app', 'Code'),
			'name' => Yii::t('app', 'Name'),
			'ageDebt' => Yii::t('app', 'Age Debt'),
			'idRegion' => Yii::t('app', 'Id Region'),
			'idState' => Yii::t('app', 'Id State'),
			'address' => Yii::t('app', 'Address'),
			'lat' => Yii::t('app', 'Lat'),
			'lng' => Yii::t('app', 'Lng'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('ageDebt', $this->ageDebt);
		$criteria->compare('idRegion', $this->idRegion);
		$criteria->compare('idState', $this->idState, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('lat', $this->lat, true);
		$criteria->compare('lng', $this->lng, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}