<?php

/**
 * This is the model base class for the table "tbl_users_profile".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersProfile".
 *
 * Columns in table "tbl_users_profile" available as properties of the model,
 * followed by relations of table "tbl_users_profile" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $descripcion
 * @property integer $active
 * @property string $dashboard
 * @property string $dateCreated
 *
 * @property LinksHelp[] $linksHelps
 * @property MenuUsersProfile[] $menuUsersProfiles
 * @property MetricsUsersProfile[] $metricsUsersProfiles
 * @property NotificationsMessages[] $notificationsMessages
 * @property UsersProfiles[] $usersProfiles
 */
abstract class BaseUsersProfile extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_users_profile';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersProfile|UsersProfiles', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('dateCreated', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('dashboard', 'length', 'max'=>50),
			array('name, descripcion', 'safe'),
			array('name, descripcion, active, dashboard', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, descripcion, active, dashboard, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'linksHelps' => array(self::HAS_MANY, 'LinksHelp', 'idUsersProfiles'),
			'menuUsersProfiles' => array(self::HAS_MANY, 'MenuUsersProfile', 'idUserProfile'),
			'metricsUsersProfiles' => array(self::HAS_MANY, 'MetricsUsersProfile', 'idUserProfile'),
			'notificationsMessages' => array(self::HAS_MANY, 'NotificationsMessages', 'idUserProfile'),
			'usersProfiles' => array(self::HAS_MANY, 'UsersProfiles', 'idUserProfile'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'active' => Yii::t('app', 'Active'),
			'dashboard' => Yii::t('app', 'Dashboard'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'linksHelps' => null,
			'menuUsersProfiles' => null,
			'metricsUsersProfiles' => null,
			'notificationsMessages' => null,
			'usersProfiles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dashboard', $this->dashboard, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}