<?php

/**
 * This is the model base class for the table "tbl_cities".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cities".
 *
 * Columns in table "tbl_cities" available as properties of the model,
 * followed by relations of table "tbl_cities" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idDepartment
 * @property string $name
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Departments $idDepartment0
 * @property Debtors[] $debtors
 * @property DebtorsAddresses[] $debtorsAddresses
 * @property DebtorsCoSigner[] $debtorsCoSigners
 * @property DebtorsPhones[] $debtorsPhones
 * @property DebtorsReference[] $debtorsReferences
 * @property DebtorsSpendings[] $debtorsSpendings
 * @property Users[] $users
 * @property UsersBusinessSpendings[] $usersBusinessSpendings
 */
abstract class BaseCities extends GxActiveRecord {
    
    public $capital;
    public $cant;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_cities';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cities|Cities', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, dateCreated', 'required'),
			array('idDepartment, active', 'numerical', 'integerOnly'=>true),
			array('idDepartment, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDepartment, name, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDepartment0' => array(self::BELONGS_TO, 'Departments', 'idDepartment'),
			'debtors' => array(self::HAS_MANY, 'Debtors', 'idCity'),
			'debtorsAddresses' => array(self::HAS_MANY, 'DebtorsAddresses', 'idCity'),
			'debtorsCoSigners' => array(self::HAS_MANY, 'DebtorsCoSigner', 'idCity'),
			'debtorsPhones' => array(self::HAS_MANY, 'DebtorsPhones', 'idCity'),
			'debtorsReferences' => array(self::HAS_MANY, 'DebtorsReference', 'idCity'),
			'debtorsSpendings' => array(self::HAS_MANY, 'DebtorsSpendings', 'idCity'),
			'users' => array(self::HAS_MANY, 'Users', 'idCity'),
			'usersBusinessSpendings' => array(self::HAS_MANY, 'UsersBusinessSpendings', 'idCity'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDepartment' => null,
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idDepartment0' => null,
			'debtors' => null,
			'debtorsAddresses' => null,
			'debtorsCoSigners' => null,
			'debtorsPhones' => null,
			'debtorsReferences' => null,
			'debtorsSpendings' => null,
			'users' => null,
			'usersBusinessSpendings' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDepartment', $this->idDepartment);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}