<?php

/**
 * This is the model base class for the table "tbl_notifications_messages".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NotificationsMessages".
 *
 * Columns in table "tbl_notifications_messages" available as properties of the model,
 * followed by relations of table "tbl_notifications_messages" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idTypeNotification
 * @property integer $idUserProfile
 * @property string $msg
 * @property string $dateCreated
 *
 * @property TblNotificationsType $idTypeNotification0
 * @property TblUsersProfile $idUserProfile0
 * @property TblUsersNotifications[] $tblUsersNotifications
 */
abstract class BaseNotificationsMessages extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_notifications_messages';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NotificationsMessages|NotificationsMessages', $n);
	}

	public static function representingColumn() {
		return 'msg';
	}

	public function rules() {
		return array(
			array('idTypeNotification, idUserProfile, msg, dateCreated', 'required'),
			array('idTypeNotification, idUserProfile', 'numerical', 'integerOnly'=>true),
			array('id, idTypeNotification, idUserProfile, msg, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'typeNot' => array(self::BELONGS_TO, 'NotificationsType', 'idTypeNotification'),
			'idUserProfile0' => array(self::BELONGS_TO, 'UsersProfile', 'idUserProfile'),
			'tblUsersNotifications' => array(self::HAS_MANY, 'UsersNotifications', 'idMessage'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idTypeNotification' => null,
			'idUserProfile' => null,
			'msg' => Yii::t('app', 'Msg'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idTypeNotification0' => null,
			'idUserProfile0' => null,
			'tblUsersNotifications' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idTypeNotification', $this->idTypeNotification);
		$criteria->compare('idUserProfile', $this->idUserProfile);
		$criteria->compare('msg', $this->msg, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}