<?php

/**
 * This is the model base class for the table "view_management_business_last".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewManagementBusinessLast".
 *
 * Columns in table "view_management_business_last" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idUsersBusiness
 * @property string $date
 *
 */
abstract class BaseViewManagementBusinessLast extends GxActiveRecord {
    
    public $days;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_management_business_last';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewManagementBusinessLast|ViewManagementBusinessLasts', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('idUsersBusiness', 'required'),
			array('idUsersBusiness', 'numerical', 'integerOnly'=>true),
			array('date', 'safe'),
			array('date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idUsersBusiness, date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idUsersBusiness' => Yii::t('app', 'Id Users Business'),
			'date' => Yii::t('app', 'Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idUsersBusiness', $this->idUsersBusiness);
		$criteria->compare('date', $this->date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}