<?php

/**
 * This is the model base class for the table "tbl_debtors_contacts_demographics".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsContactsDemographics".
 *
 * Columns in table "tbl_debtors_contacts_demographics" available as properties of the model,
 * followed by relations of table "tbl_debtors_contacts_demographics" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idDebtorContact
 * @property integer $idGender
 * @property integer $idMaritalState
 * @property integer $idOccupation
 * @property integer $incomeLegal
 * @property integer $idTypeEducationLevel
 * @property integer $dependents
 * @property integer $paymentCapacity
 * @property integer $age
 * @property integer $stratus
 * @property integer $idTypeHousing
 * @property integer $laborOld
 * @property integer $idTypeContract
 * @property integer $contractTerm
 * @property string $dateCreated
 *
 * @property DebtorsContacts $idDebtorContact0
 */
abstract class BaseDebtorsContactsDemographics extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_contacts_demographics';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsContactsDemographics|DebtorsContactsDemographics', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idDebtorContact', 'required'),
			array('idDebtorContact, idGender, idMaritalState, idOccupation, incomeLegal, idTypeEducationLevel, dependents, paymentCapacity, age, stratus, idTypeHousing, laborOld, idTypeContract, contractTerm', 'numerical', 'integerOnly'=>true,'min'=>0),
			array('idGender, idMaritalState, idOccupation, incomeLegal, idTypeEducationLevel, dependents, paymentCapacity, age, stratus, idTypeHousing, laborOld, idTypeContract, contractTerm', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDebtorContact, idGender, idMaritalState, idOccupation, incomeLegal, idTypeEducationLevel, dependents, paymentCapacity, age, stratus, idTypeHousing, laborOld, idTypeContract, contractTerm, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDebtorContact0' => array(self::BELONGS_TO, 'DebtorsContacts', 'idDebtorContact'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtorContact' => null,
			'idGender' => Yii::t('app', 'Género'),
			'idMaritalState' => Yii::t('app', 'Estado Civil'),
			'idOccupation' => Yii::t('app', 'Ocupación'),
			'idTypeDocument' => Yii::t('app', 'Id Type Document'),
			'incomeLegal' => Yii::t('app', 'Nivel de Ingresos'),
			'idTypeEducationLevel' => Yii::t('app', 'Nivel Educativo'),
			'dependents' => Yii::t('app', 'Dependientes'),
			'paymentCapacity' => Yii::t('app', 'Capacidad de Pago'),
			'age' => Yii::t('app', 'Edad'),
			'stratus' => Yii::t('app', 'Estrato'),
			'idTypeHousing' => Yii::t('app', 'Tipo de Vivienda'),
			'laborOld' => Yii::t('app', 'Antigüedad Laboral'),
			'idTypeContract' => Yii::t('app', 'Tipo de Contrato'),
			'contractTerm' => Yii::t('app', 'Plazo de Contrato'),
			'idDebtorContact0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtorContact', $this->idDebtorContact);
		$criteria->compare('idGender', $this->idGender);
		$criteria->compare('idMaritalState', $this->idMaritalState);
		$criteria->compare('idOccupation', $this->idOccupation);
		$criteria->compare('incomeLegal', $this->incomeLegal);
		$criteria->compare('idTypeEducationLevel', $this->idTypeEducationLevel);
		$criteria->compare('dependents', $this->dependents);
		$criteria->compare('paymentCapacity', $this->paymentCapacity);
		$criteria->compare('age', $this->age);
		$criteria->compare('stratus', $this->stratus);
		$criteria->compare('idTypeHousing', $this->idTypeHousing);
		$criteria->compare('laborOld', $this->laborOld);
		$criteria->compare('idTypeContract', $this->idTypeContract);
		$criteria->compare('contractTerm', $this->contractTerm);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}