<?php

/**
 * This is the model base class for the table "tbl_predictions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Predictions".
 *
 * Columns in table "tbl_predictions" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idUser
 * @property integer $idCustomer
 * @property string $source
 * @property integer $state_source
 * @property string $dataset
 * @property integer $state_dataset
 * @property string $predictions
 * @property integer $state_predictions
 * @property string $dateCreated
 *
 */
abstract class BasePredictions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_predictions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Predictions|Predictions', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('dateCreated', 'required'),
			array('idUser, idCustomer, state_source, state_dataset, state_predictions', 'numerical', 'integerOnly'=>true),
			array('source, dataset, predictions', 'length', 'max'=>200),
			array('idUser, idCustomer, source, state_source, dataset, state_dataset, predictions, state_predictions', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUser, idCustomer, source, state_source, dataset, state_dataset, predictions, state_predictions, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUser' => Yii::t('app', 'Id User'),
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'source' => Yii::t('app', 'Source'),
			'state_source' => Yii::t('app', 'State Source'),
			'dataset' => Yii::t('app', 'Dataset'),
			'state_dataset' => Yii::t('app', 'State Dataset'),
			'predictions' => Yii::t('app', 'Predictions'),
			'state_predictions' => Yii::t('app', 'State Predictions'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUser', $this->idUser);
		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('source', $this->source, true);
		$criteria->compare('state_source', $this->state_source);
		$criteria->compare('dataset', $this->dataset, true);
		$criteria->compare('state_dataset', $this->state_dataset);
		$criteria->compare('predictions', $this->predictions, true);
		$criteria->compare('state_predictions', $this->state_predictions);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}