<?php

/**
 * This is the model base class for the table "tbl_debtors_reference".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsReference".
 *
 * Columns in table "tbl_debtors_reference" available as properties of the model,
 * followed by relations of table "tbl_debtors_reference" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUserReference
 * @property integer $idDebtor
 * @property integer $idRelationshipType
 * @property integer $idCity
 * @property string $name
 * @property string $email
 * @property string $address
 * @property string $phone
 * @property string $comment
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Cities $idCity0
 * @property Debtors $idDebtor0
 * @property RelationshipType $idRelationshipType0
 * @property Users $idUserReference0
 */
abstract class BaseDebtorsReference extends GxActiveRecord {
    
    public $idCountry;
    public $idDepartment;
    public $fullDistrict;
    public $idTypeReference;
    public $state;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_reference';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsReference|DebtorsReferences', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('idUserReference, idDebtor, idCountry, idDepartment, idCity, name, email, address, phone, active', 'required'),
			array('idUserReference, idDebtor, idTypeReference, idRelationshipType, idCountry, idDepartment, idCity, active', 'numerical', 'integerOnly'=>true),
			array('name, email, address, phone', 'length', 'max'=>500),
			array('email', 'email'),
                        array('comment', 'safe'),
			array('idUserReference, idDebtor, idRelationshipType, idCity, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUserReference, idDebtor, idTypeReference, idRelationshipType, idCountry, idDepartment, idCity, name, email, address, phone, comment, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}
        
        public function afterFind(){
            parent::afterFind();                        
            
            if($this->idCity!= NULL){
                $treeDistrict = ViewLocation::model()->find(array('condition' =>'idCity ='.$this->idCity));
                if($treeDistrict != NULL){
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;                    
                }                
            } 
            
            if($this->idRelationshipType != null){
                $this->idTypeReference = $this->idRelationshipType0->idTypeReference;
            }
            
            $this->state = Yii::t('front', 'Por validar');
            if($this->active == 1){
                $this->state = Yii::t('front', 'Localizado');                
            }elseif($this->active == 2){
                $this->state = Yii::t('front', 'Ilocalizado');
            }
        }
        
        public function afterSave() {
            parent::afterSave();
            
            if($this->idCity!= NULL){
                $treeDistrict = ViewLocation::model()->find(array('condition' =>'idCity ='.$this->idCity));
                if($treeDistrict != NULL){
                    $this->idCountry = $treeDistrict->idCountry;
                    $this->idDepartment = $treeDistrict->idDepartment;
                    $this->fullDistrict = $treeDistrict->location;                    
                }                
            } 
            
            if($this->idRelationshipType != null){
                $this->idTypeReference = $this->idRelationshipType0->idTypeReference;
            }
            
            $this->state = Yii::t('front', 'Por validar');
            if($this->active == 1){
                $this->state = Yii::t('front', 'Localizado');                
            }elseif($this->active == 2){
                $this->state = Yii::t('front', 'Ilocalizado');
            }
        }

	public function relations() {
		return array(
			'idCity0' => array(self::BELONGS_TO, 'Cities', 'idCity'),
			'idDebtor0' => array(self::BELONGS_TO, 'Debtors', 'idDebtor'),
			'idRelationshipType0' => array(self::BELONGS_TO, 'RelationshipType', 'idRelationshipType'),
			'idUserReference0' => array(self::BELONGS_TO, 'Users', 'idUserReference'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUserReference' => Yii::t('front', 'Usuario'),
			'idDebtor' => Yii::t('front', 'Deudor'),
			'idTypeReference' => Yii::t('front', 'Tipo'),
			'idRelationshipType' => Yii::t('front', 'Parentesco'),
			'idCountry' => Yii::t('front', 'País'),
			'idDepartment' => Yii::t('front', 'Departamento'),
			'idCity' => Yii::t('front', 'Ciudad'),
			'name' => Yii::t('front', 'Nombre'),
			'email' => Yii::t('front', 'Email'),
			'address' => Yii::t('front', 'Dirección'),
			'phone' => Yii::t('front', 'Teléfono'),
			'comment' => Yii::t('front', 'Comentario'),
			'active' => Yii::t('front', 'Estado'),
			'dateCreated' => Yii::t('front', 'Fecha de Creación'),
			'idCity0' => null,
			'idDebtor0' => null,
			'idRelationshipType0' => null,
			'idUserReference0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUserReference', $this->idUserReference);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('idRelationshipType', $this->idRelationshipType);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}