<?php

/**
 * This is the model base class for the table "tbl_debtors_debts_reports".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsDebtsReports".
 *
 * Columns in table "tbl_debtors_debts_reports" available as properties of the model,
 * followed by relations of table "tbl_debtors_debts_reports" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idDebtorDebt
 * @property integer $idTypeReport
 * @property integer $idCreator
 * @property string $date
 * @property string $comments
 * @property string $support
 * @property string $dateCreated
 *
 * @property DebtorsDebts $idDebtorDebt0
 * @property TypeReports $idTypeReport0
 * @property Users $idCreator0
 */
abstract class BaseDebtorsDebtsReports extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_debts_reports';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsDebtsReports|DebtorsDebtsReports', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('idDebtorDebt, idTypeReport', 'required'),
			array('idDebtorDebt, idTypeReport, idCreator', 'numerical', 'integerOnly'=>true),
			array('date, comments, support', 'safe'),
			array('idCreator, support', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDebtorDebt, idTypeReport, idCreator, date, comments, support, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDebtorDebt0' => array(self::BELONGS_TO, 'DebtorsDebts', 'idDebtorDebt'),
			'idTypeReport0' => array(self::BELONGS_TO, 'TypeReports', 'idTypeReport'),
			'idCreator0' => array(self::BELONGS_TO, 'Users', 'idCreator'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtorDebt' => null,
			'idTypeReport' => null,
			'idCreator' => null,
			'date' => Yii::t('app', 'Fecha'),
			'comments' => Yii::t('app', 'Comentarios'),
			'support' => Yii::t('app', 'Soporte'),
			'dateCreated' => Yii::t('app', 'Fecha de Creación'),
			'idDebtorDebt0' => null,
			'idTypeReport0' => null,
			'idCreator0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtorDebt', $this->idDebtorDebt);
		$criteria->compare('idTypeReport', $this->idTypeReport);
		$criteria->compare('idCreator', $this->idCreator);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('comments', $this->comments, true);
		$criteria->compare('support', $this->support, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}