<?php

/**
 * This is the model base class for the table "tbl_credit_modality".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CreditModality".
 *
 * Columns in table "tbl_credit_modality" available as properties of the model,
 * followed by relations of table "tbl_credit_modality" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $label
 * @property integer $order
 * @property string $text
 * @property string $dateCreated
 *
 * @property DebtorsObligations[] $debtorsObligations
 */
abstract class BaseCreditModality extends GxActiveRecord {
    
    public $capital;
    public $cant;
    
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_credit_modality';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CreditModality|CreditModalities', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, label, text, dateCreated', 'required'),
			array('order', 'numerical', 'integerOnly'=>true),
			array('name, label', 'length', 'max'=>500),
			array('order', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, label, order, text, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'debtorsObligations' => array(self::HAS_MANY, 'DebtorsObligations', 'idCreditModality'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'label' => Yii::t('app', 'Label'),
			'order' => Yii::t('app', 'Order'),
			'text' => Yii::t('app', 'Text'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'debtorsObligations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('order', $this->order);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}