<?php

/**
 * This is the model base class for the table "tbl_users_plans".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersPlans".
 *
 * Columns in table "tbl_users_plans" available as properties of the model,
 * followed by relations of table "tbl_users_plans" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idPlan
 * @property integer $idUser
 * @property integer $accounts
 * @property string $dayPay
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Plans $idPlan0
 * @property Users $idUser0
 */
abstract class BaseUsersPlans extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_users_plans';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersPlans|UsersPlans', $n);
	}

	public static function representingColumn() {
		return 'dayPay';
	}

	public function rules() {
		return array(
			array('idPlan, idUser, accounts, active', 'numerical', 'integerOnly'=>true),
			array('dayPay, dateCreated', 'safe'),
			array('idPlan, idUser, accounts, dayPay, active, dateCreated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idPlan, idUser, accounts, dayPay, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPlan0' => array(self::BELONGS_TO, 'Plans', 'idPlan'),
			'idUser0' => array(self::BELONGS_TO, 'Users', 'idUser'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idPlan' => null,
			'idUser' => null,
			'accounts' => Yii::t('app', 'Accounts'),
			'dayPay' => Yii::t('app', 'Day Pay'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idPlan0' => null,
			'idUser0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idPlan', $this->idPlan);
		$criteria->compare('idUser', $this->idUser);
		$criteria->compare('accounts', $this->accounts);
		$criteria->compare('dayPay', $this->dayPay, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}