<?php

/**
 * This is the model base class for the table "tbl_links_help".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LinksHelp".
 *
 * Columns in table "tbl_links_help" available as properties of the model,
 * followed by relations of table "tbl_links_help" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUsersProfiles
 * @property string $name
 * @property string $link
 * @property integer $active
 * @property integer $type
 * @property string $dateCreated
 *
 * @property UsersProfile $idUsersProfiles0
 */
abstract class BaseLinksHelp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_links_help';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LinksHelp|LinksHelps', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, link, type, dateCreated', 'required'),
			array('idUsersProfiles, active, type', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('idUsersProfiles, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUsersProfiles, name, link, active, type, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUsersProfiles0' => array(self::BELONGS_TO, 'UsersProfile', 'idUsersProfiles'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUsersProfiles' => null,
			'name' => Yii::t('app', 'Name'),
			'link' => Yii::t('app', 'Link'),
			'active' => Yii::t('app', 'Active'),
			'type' => Yii::t('app', 'Type'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idUsersProfiles0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUsersProfiles', $this->idUsersProfiles);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('type', $this->type);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}