<?php

/**
 * This is the model base class for the table "view_debtors_debts_payments".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewDebtorsDebtsPayments".
 *
 * Columns in table "view_debtors_debts_payments" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idDebtorDebt
 * @property double $value
 *
 */
abstract class BaseViewDebtorsDebtsPayments extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_debtors_debts_payments';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewDebtorsDebtsPayments|ViewDebtorsDebtsPayments', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, idDebtorDebt', 'numerical', 'integerOnly'=>true),
			array('value', 'numerical'),
			array('idDebtorDebt, value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDebtorDebt, value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtorDebt' => Yii::t('app', 'Id Debtor Debt'),
			'value' => Yii::t('app', 'Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtorDebt', $this->idDebtorDebt);
		$criteria->compare('value', $this->value);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}