<?php

/**
 * This is the model base class for the table "tbl_menu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Menu".
 *
 * Columns in table "tbl_menu" available as properties of the model,
 * followed by relations of table "tbl_menu" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idMenu
 * @property string $name
 * @property string $url
 * @property string $slug
 * @property string $class
 * @property string $dateCreated
 *
 * @property Menu $idMenu0
 * @property Menu[] $menus
 * @property MenuUsersProfile[] $menuUsersProfiles
 */
abstract class BaseMenu extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_menu';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Menu|Menus', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, url, slug, class, dateCreated', 'required'),
			array('idMenu', 'numerical', 'integerOnly'=>true),
			array('name, url, slug, class', 'length', 'max'=>500),
			array('idMenu', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idMenu, name, url, slug, class, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idMenu0' => array(self::BELONGS_TO, 'Menu', 'idMenu'),
			'menus' => array(self::HAS_MANY, 'Menu', 'idMenu'),
			'menuUsersProfiles' => array(self::HAS_MANY, 'MenuUsersProfile', 'idMenu'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idMenu' => null,
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
			'slug' => Yii::t('app', 'Slug'),
			'class' => Yii::t('app', 'Class'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idMenu0' => null,
			'menus' => null,
			'menuUsersProfiles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idMenu', $this->idMenu);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('class', $this->class, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}