<?php

/**
 * This is the model base class for the table "tbl_users_business_tasks_support".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersBusinessTasksSupport".
 *
 * Columns in table "tbl_users_business_tasks_support" available as properties of the model,
 * followed by relations of table "tbl_users_business_tasks_support" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUserBusinessSupport
 * @property integer $idUserBusinessTask
 * @property string $support
 * @property string $dateCreated
 *
 * @property Users $idUserBusinessSupport0
 * @property UsersBusinessTasks $idUserBusinessTask0
 */
abstract class BaseUsersBusinessTasksSupport extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_users_business_tasks_support';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersBusinessTasksSupport|UsersBusinessTasksSupports', $n);
	}

	public static function representingColumn() {
		return 'support';
	}

	public function rules() {
		return array(
			array('idUserBusinessTask, support', 'required'),
			array('idUserBusinessSupport, idUserBusinessTask', 'numerical', 'integerOnly'=>true),
			array('idUserBusinessSupport', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUserBusinessSupport, idUserBusinessTask, support, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUserBusinessSupport0' => array(self::BELONGS_TO, 'Users', 'idUserBusinessSupport'),
			'idUserBusinessTask0' => array(self::BELONGS_TO, 'UsersBusinessTasks', 'idUserBusinessTask'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUserBusinessSupport' => null,
			'idUserBusinessTask' => null,
			'support' => Yii::t('app', 'Support'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idUserBusinessSupport0' => null,
			'idUserBusinessTask0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUserBusinessSupport', $this->idUserBusinessSupport);
		$criteria->compare('idUserBusinessTask', $this->idUserBusinessTask);
		$criteria->compare('support', $this->support, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}