<?php

/**
 * This is the model base class for the table "tbl_debtors_obligations_legal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DebtorsObligationsLegal".
 *
 * Columns in table "tbl_debtors_obligations_legal" available as properties of the model,
 * followed by relations of table "tbl_debtors_obligations_legal" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idDebtorObligation
 * @property integer $idOfficeLegal
 * @property integer $idCategoryLegal
 * @property integer $OfficeNumber
 * @property string $addressOfficeLegal
 * @property string $settledNumber
 * @property string $attorney
 * @property string $dateCreated
 *
 * @property DebtorsObligations $idDebtorObligation0
 */
abstract class BaseDebtorsObligationsLegal extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_debtors_obligations_legal';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DebtorsObligationsLegal|DebtorsObligationsLegals', $n);
	}

	public static function representingColumn() {
		return 'addressOfficeLegal';
	}

	public function rules() {
		return array(
			array('idOfficeLegal, idCategoryLegal, OfficeNumber, addressOfficeLegal, settledNumber, attorney', 'required'),
			array('idDebtorObligation, idOfficeLegal, idCategoryLegal, OfficeNumber', 'numerical', 'integerOnly'=>true),
			array('addressOfficeLegal, settledNumber, attorney', 'length', 'max'=>500),
			array('dateCreated', 'safe'),
			array('idDebtorObligation, dateCreated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idDebtorObligation, idOfficeLegal, idCategoryLegal, OfficeNumber, addressOfficeLegal, settledNumber, attorney, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDebtorObligation0' => array(self::BELONGS_TO, 'DebtorsObligations', 'idDebtorObligation'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idDebtorObligation' => null,
			'idOfficeLegal' => Yii::t('app', 'Id Office Legal'),
			'idCategoryLegal' => Yii::t('app', 'Id Category Legal'),
			'OfficeNumber' => Yii::t('app', 'Office Number'),
			'addressOfficeLegal' => Yii::t('app', 'Address Office Legal'),
			'settledNumber' => Yii::t('app', 'Settled Number'),
			'attorney' => Yii::t('app', 'Attorney'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idDebtorObligation0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtorObligation', $this->idDebtorObligation);
		$criteria->compare('idOfficeLegal', $this->idOfficeLegal);
		$criteria->compare('idCategoryLegal', $this->idCategoryLegal);
		$criteria->compare('OfficeNumber', $this->OfficeNumber);
		$criteria->compare('addressOfficeLegal', $this->addressOfficeLegal, true);
		$criteria->compare('settledNumber', $this->settledNumber, true);
		$criteria->compare('attorney', $this->attorney, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}