<?php

/**
 * This is the model base class for the table "tbl_countries".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Countries".
 *
 * Columns in table "tbl_countries" available as properties of the model,
 * followed by relations of table "tbl_countries" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $active
 * @property string $code
 * @property string $indicative
 * @property string $dateCreated
 *
 * @property Departments[] $departments
 */
abstract class BaseCountries extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_countries';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Countries|Countries', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('dateCreated', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>255),
                        array('indicative', 'length', 'max'=>25),
			array('name', 'safe'),
			array('name, active, code, indicative', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, active, code, indicative, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'departments' => array(self::HAS_MANY, 'Departments', 'idCountry'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'code' => Yii::t('app', 'Code'),
                        'indicative' => Yii::t('app', 'Indicative'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'departments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('code', $this->code, true);
                $criteria->compare('indicative', $this->indicative, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}