<?php

/**
 * This is the model base class for the table "view_historic".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewHistoric".
 *
 * Columns in table "view_historic" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idCustomer
 * @property string $customer
 * @property integer $idCreditModality
 * @property integer $id
 * @property integer $idDebtor
 * @property string $name
 * @property integer $idTypeDocument
 * @property string $code
 * @property string $duedate
 * @property double $capital
 * @property integer $is_legal
 * @property string $idCity
 * @property string $city
 * @property string $idState
 * @property string $state
 * @property string $idDebtorSubstate
 *
 */
abstract class BaseViewHistoric extends GxActiveRecord {
    
    public $date;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_historic';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewHistoric|ViewHistorics', $n);
	}

	public static function representingColumn() {
		return 'idCity';
	}

	public function rules() {
		return array(
			array('idCustomer, idCreditModality, id, idDebtor, idTypeDocument, is_legal', 'numerical', 'integerOnly'=>true),
			array('capital', 'numerical'),
			array('idCity', 'length', 'max'=>11),
			array('idState, idDebtorSubstate', 'length', 'max'=>255),
			array('customer, name, code, duedate, city, state', 'safe'),
			array('idCustomer, customer, idCreditModality, id, idDebtor, name, idTypeDocument, code, duedate, capital, is_legal, idCity, city, idState, state, idDebtorSubstate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idCustomer, customer, idCreditModality, id, idDebtor, name, idTypeDocument, code, duedate, capital, is_legal, idCity, city, idState, state, idDebtorSubstate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idCustomer' => Yii::t('app', 'Id Customer'),
			'customer' => Yii::t('app', 'Customer'),
			'idCreditModality' => Yii::t('app', 'Id Credit Modality'),
			'id' => Yii::t('app', 'ID'),
			'idDebtor' => Yii::t('app', 'Id Debtor'),
			'name' => Yii::t('app', 'Name'),
			'idTypeDocument' => Yii::t('app', 'Id Type Document'),
			'code' => Yii::t('app', 'Code'),
			'duedate' => Yii::t('app', 'Duedate'),
			'capital' => Yii::t('app', 'Capital'),
			'is_legal' => Yii::t('app', 'Is Legal'),
			'idCity' => Yii::t('app', 'Id City'),
			'city' => Yii::t('app', 'City'),
			'idState' => Yii::t('app', 'Id State'),
			'state' => Yii::t('app', 'State'),
			'idDebtorSubstate' => Yii::t('app', 'Id Debtor Substate'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idCustomer', $this->idCustomer);
		$criteria->compare('customer', $this->customer, true);
		$criteria->compare('idCreditModality', $this->idCreditModality);
		$criteria->compare('id', $this->id);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('idTypeDocument', $this->idTypeDocument);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('duedate', $this->duedate, true);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('is_legal', $this->is_legal);
		$criteria->compare('idCity', $this->idCity, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('idState', $this->idState, true);
		$criteria->compare('state', $this->state, true);
		$criteria->compare('idDebtorSubstate', $this->idDebtorSubstate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}