<?php

/**
 * This is the model base class for the table "tbl_type_import".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TypeImport".
 *
 * Columns in table "tbl_type_import" available as properties of the model,
 * followed by relations of table "tbl_type_import" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $template
 * @property integer $active
 * @property string $dateCreated
 *
 * @property TblUsersImport[] $tblUsersImports
 */
abstract class BaseTypeImport extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_type_import';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TypeImport|TypeImports', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description, template, dateCreated', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('name, template', 'length', 'max'=>255),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, template, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tblUsersImports' => array(self::HAS_MANY, 'TblUsersImport', 'idTypeImport'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'template' => Yii::t('app', 'Template'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'tblUsersImports' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('template', $this->template, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}