<?php

/**
 * This is the model base class for the table "tbl_currencies".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Currencies".
 *
 * Columns in table "tbl_currencies" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $currency
 * @property string $value
 * @property string $dateCreated
 *
 */
abstract class BaseCurrencies extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_currencies';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Currencies|Currencies', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, currency, value, dateCreated', 'required'),
			array('name, currency', 'length', 'max'=>50),
			 array('value', 'numerical', 'integerOnly'=>false),
			array('id, name, currency, value, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'currency' => Yii::t('app', 'Currency'),
			'value' => Yii::t('app', 'Value'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('currency', $this->currency, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}