<?php

/**
 * This is the model base class for the table "tbl_users_business".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersBusiness".
 *
 * Columns in table "tbl_users_business" available as properties of the model,
 * followed by relations of table "tbl_users_business" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idUser
 * @property integer $idUserState
 * @property integer $idUserBusiness
 * @property integer $idBusinessAdvisor
 * @property integer $idSector
 * @property string $value
 * @property string $date_close
 * @property string $dateCreated
 *
 * @property Sectors $idSector0
 * @property Users $idUser0
 * @property Users $idUserBusiness0
 * @property Users $idBusinessAdvisor0
 * @property UsersState $idUserState0
 * @property UsersBusinessSpendings[] $usersBusinessSpendings
 * @property UsersBusinessTasks[] $usersBusinessTasks
 */
abstract class BaseUsersBusiness extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_users_business';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersBusiness|UsersBusinesses', $n);
	}

	public static function representingColumn() {
		return 'date_close';
	}

	public function rules() {
		return array(
			array('idUser, date_close', 'required'),
			array('idUser, idUserState, idUserBusiness, idBusinessAdvisor, value, idSector', 'numerical', 'integerOnly'=>true),
			array('value', 'length', 'max'=>20),
			array('idUserState, idUserBusiness, idBusinessAdvisor, idSector, value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idUser, idUserState, idUserBusiness, idBusinessAdvisor, idSector, value, date_close, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idSector0' => array(self::BELONGS_TO, 'Sectors', 'idSector'),
			'idUser0' => array(self::BELONGS_TO, 'Users', 'idUser'),
			'idUserBusiness0' => array(self::BELONGS_TO, 'Users', 'idUserBusiness'),
			'idBusinessAdvisor0' => array(self::BELONGS_TO, 'Users', 'idBusinessAdvisor'),
			'idUserState0' => array(self::BELONGS_TO, 'UsersState', 'idUserState'),
			'usersBusinessSpendings' => array(self::HAS_MANY, 'UsersBusinessSpendings', 'idUserBusiness'),
			'usersBusinessTasks' => array(self::HAS_MANY, 'UsersBusinessTasks', 'idUsersBusiness'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idUser' => null,
			'idUserState' => null,
			'idUserBusiness' => null,
			'idBusinessAdvisor' => null,
			'idSector' => null,
			'value' => Yii::t('app', 'Value'),
			'date_close' => Yii::t('app', 'Date Close'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idSector0' => null,
			'idUser0' => null,
			'idUserBusiness0' => null,
			'idBusinessAdvisor0' => null,
			'idUserState0' => null,
			'usersBusinessSpendings' => null,
			'usersBusinessTasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idUser', $this->idUser);
		$criteria->compare('idUserState', $this->idUserState);
		$criteria->compare('idUserBusiness', $this->idUserBusiness);
		$criteria->compare('idBusinessAdvisor', $this->idBusinessAdvisor);
		$criteria->compare('idSector', $this->idSector);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('date_close', $this->date_close, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}