<?php

/**
 * This is the model base class for the table "tbl_mlmodels_fields".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MlmodelsFields".
 *
 * Columns in table "tbl_mlmodels_fields" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $name_export
 * @property string $db
 * @property string $type
 * @property integer $active
 * @property string $dateCreated
 *
 */
abstract class BaseMlmodelsFields extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_mlmodels_fields';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MlmodelsFields|MlmodelsFields', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, name_export, db, type, dateCreated', 'required'),
			array('active', 'numerical', 'integerOnly'=>true),
			array('name, name_export, db', 'length', 'max'=>50),
			array('type', 'length', 'max'=>5),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, name_export, db, type, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'name_export' => Yii::t('app', 'Name Export'),
			'db' => Yii::t('app', 'Db'),
			'type' => Yii::t('app', 'Type'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('name_export', $this->name_export, true);
		$criteria->compare('db', $this->db, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}