<?php

/**
 * This is the model base class for the table "tbl_assignments_debtors_advisers".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AssignmentsDebtorsAdvisers".
 *
 * Columns in table "tbl_assignments_debtors_advisers" available as properties of the model,
 * followed by relations of table "tbl_assignments_debtors_advisers" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idAdviser
 * @property integer $idDebtor
 * @property integer $idUserImport
 * @property integer $idUserCreator
 * @property string $dateCreated
 *
 * @property Debtors $idDebtor0
 * @property Users $idAdviser0
 * @property Users $idUserCreator0
 * @property UsersImport $idUserImport0
 */
abstract class BaseAssignmentsDebtorsAdvisers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_assignments_debtors_advisers';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AssignmentsDebtorsAdvisers|AssignmentsDebtorsAdvisers', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('idAdviser, idDebtor, dateCreated', 'required'),
			array('idAdviser, idDebtor, idUserImport, idUserCreator', 'numerical', 'integerOnly'=>true),
			array('idUserImport, idUserCreator', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idAdviser, idDebtor, idUserImport, idUserCreator, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDebtor0' => array(self::BELONGS_TO, 'Debtors', 'idDebtor'),
			'idAdviser0' => array(self::BELONGS_TO, 'Users', 'idAdviser'),
			'idUserCreator0' => array(self::BELONGS_TO, 'Users', 'idUserCreator'),
			'idUserImport0' => array(self::BELONGS_TO, 'UsersImport', 'idUserImport'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idAdviser' => null,
			'idDebtor' => null,
			'idUserImport' => null,
			'idUserCreator' => null,
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idDebtor0' => null,
			'idAdviser0' => null,
			'idUserCreator0' => null,
			'idUserImport0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idAdviser', $this->idAdviser);
		$criteria->compare('idDebtor', $this->idDebtor);
		$criteria->compare('idUserImport', $this->idUserImport);
		$criteria->compare('idUserCreator', $this->idUserCreator);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}