<?php

/**
 * This is the model base class for the table "tbl_tempo_centroid".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TempoCentroid".
 *
 * Columns in table "tbl_tempo_centroid" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $idMLModel
 * @property integer $idDebtorObligation
 * @property string $cluster
 * @property integer $migrate
 * @property string $lot
 * @property string $dateCreated
 *
 */
abstract class BaseTempoCentroid extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tempo_centroid';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TempoCentroid|TempoCentroids', $n);
	}

	public static function representingColumn() {
		return 'lot';
	}

	public function rules() {
		return array(
			array('lot, dateCreated', 'required'),
			array('idMLModel, idDebtorObligation, migrate', 'numerical', 'integerOnly'=>true),
			array('cluster', 'safe'),
			array('idMLModel, idDebtorObligation, cluster, migrate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idMLModel, idDebtorObligation, cluster, migrate, lot, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idMLModel' => Yii::t('app', 'Id Mlmodel'),
			'idDebtorObligation' => Yii::t('app', 'Id Debtor Obligation'),
			'cluster' => Yii::t('app', 'Cluster'),
			'migrate' => Yii::t('app', 'Migrate'),
			'lot' => Yii::t('app', 'Lot'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idMLModel', $this->idMLModel);
		$criteria->compare('idDebtorObligation', $this->idDebtorObligation);
		$criteria->compare('cluster', $this->cluster, true);
		$criteria->compare('migrate', $this->migrate);
		$criteria->compare('lot', $this->lot, true);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}