<?php

/**
 * This is the model base class for the table "tbl_tasks_actions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TasksActions".
 *
 * Columns in table "tbl_tasks_actions" available as properties of the model,
 * followed by relations of table "tbl_tasks_actions" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idTasksAction
 * @property string $name
 * @property integer $active
 * @property integer $is_legal
 * @property string $dateCreated
 *
 * @property DebtorsTasks[] $debtorsTasks
 * @property DebtorsTasks[] $debtorsTasks1
 * @property TasksActions $idTasksAction0
 * @property TasksActions[] $tasksActions
 * @property UsersBusinessTasks[] $usersBusinessTasks
 */
abstract class BaseTasksActions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_tasks_actions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TasksActions|TasksActions', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, dateCreated', 'required'),
			array('idTasksAction, active, is_legal', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>500),
			array('idTasksAction, active, is_legal', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idTasksAction, name, active, is_legal, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'debtorsTasks' => array(self::HAS_MANY, 'DebtorsTasks', 'idTasksAction'),
			'debtorsTasks1' => array(self::HAS_MANY, 'DebtorsTasks', 'idTasksEffect'),
			'idTasksAction0' => array(self::BELONGS_TO, 'TasksActions', 'idTasksAction'),
			'tasksActions' => array(self::HAS_MANY, 'TasksActions', 'idTasksAction'),
			'usersBusinessTasks' => array(self::HAS_MANY, 'UsersBusinessTasks', 'idTasksAction'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idTasksAction' => null,
			'name' => Yii::t('app', 'Name'),
			'active' => Yii::t('app', 'Active'),
			'is_legal' => Yii::t('app', 'Is Legal'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'debtorsTasks' => null,
			'debtorsTasks1' => null,
			'idTasksAction0' => null,
			'tasksActions' => null,
			'usersBusinessTasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idTasksAction', $this->idTasksAction);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('is_legal', $this->is_legal);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}