<?php

/**
 * This is the model base class for the table "view_debtors_obligations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewDebtorsObligations".
 *
 * Columns in table "view_debtors_obligations" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $credit_number
 * @property string $duedate
 * @property string $expeditionDate
 * @property string $prescription
 * @property double $capital
 * @property double $interestMonth
 * @property double $interest
 * @property double $fee
 * @property string $dayDebt
 * @property string $monthDebt
 * @property integer $active
 * @property string $dateCreated
 *
 */
abstract class BaseViewDebtorsObligations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_debtors_obligations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewDebtorsObligations|ViewDebtorsObligations', $n);
	}

	public static function representingColumn() {
		return 'credit_number';
	}

	public function rules() {
		return array(
			array('id, credit_number, duedate, capital, active, dateCreated', 'required'),
			array('id, active', 'numerical', 'integerOnly'=>true),
			array('capital, interestMonth, interest, fee', 'numerical'),
			array('dayDebt, monthDebt', 'length', 'max'=>21),
			array('expeditionDate, prescription', 'safe'),
			array('expeditionDate, prescription, interestMonth, interest, fee, dayDebt, monthDebt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, credit_number, duedate, expeditionDate, prescription, capital, interestMonth, interest, fee, dayDebt, monthDebt, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'credit_number' => Yii::t('app', 'Credit Number'),
			'duedate' => Yii::t('app', 'Duedate'),
			'expeditionDate' => Yii::t('app', 'Expedition Date'),
			'prescription' => Yii::t('app', 'Prescription'),
			'capital' => Yii::t('app', 'Capital'),
			'interestMonth' => Yii::t('app', 'Interest Month'),
			'interest' => Yii::t('app', 'Interest'),
			'fee' => Yii::t('app', 'Fee'),
			'dayDebt' => Yii::t('app', 'Day Debt'),
			'monthDebt' => Yii::t('app', 'Month Debt'),
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('credit_number', $this->credit_number, true);
		$criteria->compare('duedate', $this->duedate, true);
		$criteria->compare('expeditionDate', $this->expeditionDate, true);
		$criteria->compare('prescription', $this->prescription, true);
		$criteria->compare('capital', $this->capital);
		$criteria->compare('interestMonth', $this->interestMonth);
		$criteria->compare('interest', $this->interest);
		$criteria->compare('fee', $this->fee);
		$criteria->compare('dayDebt', $this->dayDebt, true);
		$criteria->compare('monthDebt', $this->monthDebt, true);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}