<?php

/**
 * This is the model base class for the table "tbl_campaigns_coordinators".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CampaignsCoordinators".
 *
 * Columns in table "tbl_campaigns_coordinators" available as properties of the model,
 * followed by relations of table "tbl_campaigns_coordinators" available as properties of the model.
 *
 * @property integer $id
 * @property integer $idCampaign
 * @property integer $idCoordinator
 * @property integer $active
 * @property string $dateCreated
 *
 * @property Campaigns $idCampaign0
 * @property Users $idCoordinator0
 */
abstract class BaseCampaignsCoordinators extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_campaigns_coordinators';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CampaignsCoordinators|CampaignsCoordinators', $n);
	}

	public static function representingColumn() {
		return 'dateCreated';
	}

	public function rules() {
		return array(
			array('dateCreated', 'required'),
			array('idCampaign, idCoordinator, active', 'numerical', 'integerOnly'=>true),
			array('idCampaign, idCoordinator, active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, idCampaign, idCoordinator, active, dateCreated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCampaign0' => array(self::BELONGS_TO, 'Campaigns', 'idCampaign'),
			'idCoordinator0' => array(self::BELONGS_TO, 'Users', 'idCoordinator'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idCampaign' => null,
			'idCoordinator' => null,
			'active' => Yii::t('app', 'Active'),
			'dateCreated' => Yii::t('app', 'Date Created'),
			'idCampaign0' => null,
			'idCoordinator0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('idCampaign', $this->idCampaign);
		$criteria->compare('idCoordinator', $this->idCoordinator);
		$criteria->compare('active', $this->active);
		$criteria->compare('dateCreated', $this->dateCreated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}