<?php

/**
 * This is the model base class for the table "view_maps_business".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewMapsBusiness".
 *
 * Columns in table "view_maps_business" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $numberDocument
 * @property string $name
 * @property integer $idCity
 * @property integer $idRegion
 * @property integer $idUserState
 * @property integer $idBusinessAdvisor
 * @property string $address
 * @property string $lat
 * @property string $lng
 *
 */
abstract class BaseViewMapsBusiness extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_maps_business';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewMapsBusiness|ViewMapsBusinesses', $n);
	}

	public static function representingColumn() {
		return 'numberDocument';
	}

	public function rules() {
		return array(
			array('id, idCity, idRegion, idUserState, idBusinessAdvisor', 'numerical', 'integerOnly'=>true),
			array('numberDocument, name, address, lat, lng', 'safe'),
			array('id, numberDocument, name, idCity, idRegion, idUserState, idBusinessAdvisor, address, lat, lng', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, numberDocument, name, idCity, idRegion, idUserState, idBusinessAdvisor, address, lat, lng', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'numberDocument' => Yii::t('app', 'Number Document'),
			'name' => Yii::t('app', 'Name'),
			'idCity' => Yii::t('app', 'Id City'),
			'idRegion' => Yii::t('app', 'Id Region'),
			'idUserState' => Yii::t('app', 'Id User State'),
			'idBusinessAdvisor' => Yii::t('app', 'Id Business Advisor'),
			'address' => Yii::t('app', 'Address'),
			'lat' => Yii::t('app', 'Lat'),
			'lng' => Yii::t('app', 'Lng'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('numberDocument', $this->numberDocument, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('idCity', $this->idCity);
		$criteria->compare('idRegion', $this->idRegion);
		$criteria->compare('idUserState', $this->idUserState);
		$criteria->compare('idBusinessAdvisor', $this->idBusinessAdvisor);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('lat', $this->lat, true);
		$criteria->compare('lng', $this->lng, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        //'sort' => array('defaultOrder'=>'orden')
		));
	}
}